### ISSUE TITLE
Add Baystate Health

### ISSUE THREAD

**Issue by harcod** [livgust/covid-vaccine-scrapers#168] opened 2021-03-22 19:23 UTC
https://workwell.apps.baystatehealth.org/guest/covid-vaccine/register?r=mafirstresp210121

**Comment by kriation** [comment] 2021-03-24 00:47
@harcod Is this a duplicate of #11? The closed PR is #102.

**Comment by harcod** [comment] 2021-03-24 01:11
I got the url from @livgust

**Comment by kriation** [comment] 2021-03-24 01:46
@harcod - Yep. That's the [link](https://github.com/livgust/covid-vaccine-scrapers/pull/102/files#diff-03ffc9e6023468d2a06c339dad2e153949362b8aa6be81204ff1666e5ff4ab8eR399) I used in the scraper.

**Closed** 2021-04-01 13:37 UTC
Labels: availability scraping
